# src/main/resources/application-prod.yml
spring:
  datasource:
    url: >-
      jdbc:snowflake://${SNOWFLAKE_ACCOUNT}.snowflakecomputing.com
      ?warehouse=${SNOWFLAKE_WAREHOUSE}
      &db=${SNOWFLAKE_DATABASE}
      &JDBC_QUERY_RESULT_FORMAT=JSON
    username: ${SNOWFLAKE_USER}
    password: ${SNOWFLAKE_PWD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      data-source-properties:
        ENABLE_ARROW_RESULTSET: false

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO