spring:
  application:
    name: ph-shoes-etl

  datasource:
    driver-class-name: net.snowflake.client.jdbc.SnowflakeDriver
    # Keep URL on ONE line
    url: "jdbc:snowflake://${SNOWFLAKE_ACCOUNT}.snowflakecomputing.com/?warehouse=${SNOWFLAKE_WAREHOUSE:COMPUTE_WH}&db=${SNOWFLAKE_DATABASE}&schema=${SNOWFLAKE_SCHEMA:PUBLIC}&role=${SNOWFLAKE_ROLE}"
    username: ${SNOWFLAKE_USER}
    password: ${SNOWFLAKE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 30000
      data-source-properties:
        # keep Arrow off to avoid native deps
        ENABLE_ARROW_RESULTSET: false
        CLIENT_SESSION_KEEP_ALIVE: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SnowflakeDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
