# src/main/resources/application-dev.yml
spring:
  datasource:
    url: >-
      jdbc:snowflake://${SNOWFLAKE_ACCOUNT}.snowflakecomputing.com
      ?warehouse=${SNOWFLAKE_WAREHOUSE}
      &db=${SNOWFLAKE_DATABASE}
      &schema=${SNOWFLAKE_SCHEMA}
      &JDBC_QUERY_RESULT_FORMAT=JSON
    username: ${SNOWFLAKE_USER}
    password: ${SNOWFLAKE_PWD}
    driver-class-name: net.snowflake.client.jdbc.SnowflakeDriver
    hikari:
      data-source-properties:
        ENABLE_ARROW_RESULTSET: false

  jpa:
    show-sql: true